# Generated by Django 5.1.1 on 2024-10-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0006_remove_runningevent_distances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningevent',
            name='distances',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='running_app.distance'),
        ),
    ]
