# Generated by Django 5.1.1 on 2024-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0008_distance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='city',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='state',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
