# Generated by Django 5.1.1 on 2024-10-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0009_alter_distance_name_alter_runningevent_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='runningevent',
            name='distances',
        ),
        migrations.AddField(
            model_name='distance',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='running_app.runningevent'),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
