# Generated by Django 5.1.1 on 2024-10-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0010_remove_distance_name_remove_runningevent_distances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='events',
        ),
        migrations.AddField(
            model_name='distance',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='runningevent',
            name='distance',
            field=models.ManyToManyField(related_name='distances', to='running_app.distance'),
        ),
    ]
