# Generated by Django 5.1.1 on 2024-10-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0012_alter_distance_options_alter_runningevent_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningevent',
            name='state_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
