# Generated by Django 5.1.1 on 2024-10-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0013_runningevent_state_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningevent',
            name='state_img',
        ),
    ]
