# Generated by Django 5.1.1 on 2024-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0014_remove_runningevent_state_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
