# Generated by Django 5.1.1 on 2024-10-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0016_runningevent_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningevent',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='runningevent',
            name='type',
            field=models.CharField(blank=True, default='running', max_length=200, null=True),
        ),
    ]
