# Generated by Django 5.1.1 on 2024-10-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0018_alter_runningevent_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningevent',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
