# Generated by Django 5.1.1 on 2024-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0021_alter_runningevent_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningevent',
            name='distance',
            field=models.ManyToManyField(blank=True, to='running_app.distance'),
        ),
    ]
