# Generated by Django 5.1.1 on 2024-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0022_alter_runningevent_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningevent',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
