# Generated by Django 5.1.1 on 2024-10-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_app', '0023_alter_runningevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningevent',
            name='last_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='runningevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
